### PR TITLE
Add missing DGL_NAMESPACE qualifier

### PR DESCRIPTION
**Pull request by thirtythreeforty**
Fixes a build failure on MSVC when building with `DONT_SET_USING_DGL_NAMESPACE`:

    distrho\src\DistrhoUIInternal.hpp(270,39): error C2061: syntax error: identifier 'IdleCallback'
      (compiling source file 'distrho/DistrhoPluginMain.cpp')

### CODE REVIEW

**Comment by falkTX** [comment]
I wanted to have some CI checks that failed this automatically, done in #480 which now replaces this.
Thanks anyhow
